### ISSUE TITLE
Bug with string escape in complex commands

### ISSUE THREAD

**Issue by emitrackman** [jasursadikov/mud#62]
When I try to use some more advanced scripting it looks like mud is altering the passed string that should otherwise be pass through (because of single quotes).

```
mud -t -a bash -c '[ -f ./path/to/file.txt ] && nvr --remote ./path/to/file.txt' 
```

will give 

```
-f: line 1: [: missing `]'
```

While it clearly has closing ']'

**Comment by jasursadikov** [comment]
Yeah, I see it is loosing `'` on the way. I will investigate.

**Comment by jasursadikov** [comment]
@emitrackman Alternatively, you can try using `"' '"` instead of `'`
